"""Base classes for map layers in LLMaps.

The layer system is intentionally light-weight: each concrete layer is a
small dataclass that knows how to convert itself into a MapLibre‑friendly
configuration dictionary.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Mapping, Optional

from ..sources.base import BaseSource


@dataclass
class BaseLayer:
    """Common attributes for all map layers.

    Parameters
    ----------
    id:
        Unique layer identifier. If omitted, it should be generated by
        higher-level code; in practice most users will pass a short ID.
    source:
        Data source used by this layer.
    visible:
        Initial visibility flag.
    minzoom, maxzoom:
        Optional zoom constraints for the layer.
    feature_state:
        Optional dict mapping feature-state keys to GeoJSON property names
        (strings) or constant values (bool/number).  When set, the library
        automatically generates JS that iterates over source features after
        loading and calls ``map.setFeatureState`` for each one.

        Example::

            feature_state={"active": True, "color": "POP_EST"}

        Here ``active`` is a constant ``True`` for every feature, while
        ``color`` reads the ``POP_EST`` property from each GeoJSON feature.
        Requires ``promote_id`` on the corresponding source.
    """

    id: str
    source: BaseSource
    visible: bool = True
    minzoom: Optional[float] = None
    maxzoom: Optional[float] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    feature_state: Optional[Dict[str, Any]] = None

    layer_type: str = "base"

    def to_dict(self) -> Dict[str, Any]:
        """Return a generic layer configuration dictionary.

        Concrete subclasses should extend the returned dict with
        type-specific paint/layout properties.
        """

        config: Dict[str, Any] = {
            "id": self.id,
            "type": self.layer_type,
            "source": self.source.id,
            "visible": self.visible,
            "metadata": dict(self.metadata),
        }

        if self.minzoom is not None:
            config["minzoom"] = self.minzoom
        if self.maxzoom is not None:
            config["maxzoom"] = self.maxzoom
        if self.feature_state is not None:
            config["featureState"] = self.feature_state

        return config

